################################################################################
#
# hailort driver
#
################################################################################i

HAILORT_DRIVER_VERSION = v4.20.0
HAILORT_DRIVER_SITE = https://github.com/hailo-ai/hailort.git
HAILORT_DRIVER_SITE_METHOD = git
HAILORT_DRIVER_GIT_SUBMODULES = YES
HAILORT_DRIVER_LICENSE = MIT
HAILORT_DRIVER_DEPENDENCIES = spdlog protobuf eigen
HAILORT_DRIVER_INSTALL_STAGING = YES

HAILORT_DRIVER_CONF_OPTS += -Bbuild
HAILORT_DRIVER_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF

define HAILORT_DRIVER_BUILD_CMDS
    $(HOST_MAKE_ENV) $(HAILORT_DRIVER_BUILD_ENV) $(BR2_CMAKE) --build $(HAILORT_DRIVER_BUILDDIR)/build/ -j$(PARALLEL_JOBS) $(HAILORT_DRIVER_BUILD_OPTS)
endef

define HAILORT_DRIVER_INSTALL_STAGING_CMDS
    $(TARGET_MAKE_ENV) $(HAILORT_DRIVER_BUILD_ENV) DESTDIR=$(STAGING_DIR) $(BR2_CMAKE) --install $(HAILORT_DRIVER_BUILDDIR)/build/ $(HAILORT_DRIVER_INSTALL_TARGET_OPTS)
endef

define HAILORT_DRIVER_INSTALL_TARGET_CMDS
    $(TARGET_MAKE_ENV) $(HAILORT_DRIVER_BUILD_ENV) DESTDIR=$(TARGET_DIR) $(BR2_CMAKE) --install $(HAILORT_DRIVER_BUILDDIR)/build/ $(HAILORT_DRIVER_INSTALL_TARGET_OPTS)
endef

$(eval $(cmake-package))
